config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  resources :people
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
    validates :name, presence: true,
                     length: { minimum: 2 }
    validates :favoritecity, presence: true,
                     length: { minimum: 2 }
                     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  

  
  def index
      @people = Person.all
  end
  
  def show
      @person = Person.find(params[:id])
  end
  
  def new
      @person = Person.new
  end
  
  def edit
      @person = Person.find(params[:id])
  end
  
  def create
      @person = Person.new(person_params)
      
      if @person.save
          redirect_to @person
      else
        render 'new'
      end
  end
  
  def update
      @person = Person.find(params[:id])
      
      if @person.update(person_params)
          redirect_to @person
          else
          render 'edit'
      end
  end
  
  def destroy
      @person = Person.find(params[:id])
      @person.destroy
      
      redirect_to people_path
  end
  
  private
    def person_params
        params.require(:person).permit(:name, :favoritecity)
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myspotify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>Editing person</h1>
 
<%= form_for :person, url: person_path(@person), method: :patch do |f| %>
 
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@person.errors.count, "error") %> prohibited
        this person's info from being saved:
      </h2>
      <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
   <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :favoritecity, "Favorite City" %><br>
    <%= f.text_field :favoritecity %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing People</h1>

<%= link_to 'New person', new_person_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Favorite City</th>
    <th colspan="2"></th>
  </tr>

  <% @people.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><%= person.favoritecity %></td>
    <td><%= link_to 'Show', person_path(person) %></td>
     <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person_path(person),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>

<%= link_to 'Back', controller: 'welcome' %>

app/views/people/new.html.erb
<h1>New Person</h1>
<%= form_for :person, url: people_path do |f|%>

  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@person.errors.count, "error") %> prohibited
        this person's info from being saved:
      </h2>
      <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :favoritecity, "Favorite City" %><br>
    <%= f.text_field :favoritecity %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= form_for :person, url: people_path do |f| %>
  ...
<% end %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p>
  <strong>Name:</strong>
  <%=@person.name %>
</p>

<p>
  <strong>Favorite City:</strong>
  <%= @person.favoritecity %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/welcome/index.html.erb
<h1>Hello again, People!</h1>
<%= link_to 'My People', controller: 'people' %>